### ISSUE TITLE
add a button to save instantaneous image as fits file

### ISSUE THREAD

**Issue by bxin** [lsst-sitcom/spot_motion_monitor#49]
For data analysis it would be useful to be able to take a ROI frame and save to fits file in the data dir. A delay (even up to a few seconds) would be OK. This would be very useful in evaluating the actual intensity profile, including SNR and the intensity ratio between the rings and the core, etc.
Perhaps a button on the GUI?

**Comment by mareuter** [comment]
This will be satisfied by #52.

**Comment by bxin** [comment]
PR reviewed and merged
