### ISSUE TITLE
create a new data file when the ROI mode is restarted

### ISSUE THREAD

**Issue by bxin** [lsst-sitcom/spot_motion_monitor#50]
Right now the behavior is that when the user stops ROI mode, changes some settings, then restart ROI, the UI would append new entries to the previous data file. As a temporary workaround, we have been moving files out of the data folder when the ROI mode is restarted. We should write to a new data file when the ROI mode gets restarted.

**Comment by mareuter** [comment]
This was fixed in release 2.0.3.
